set_property PACKAGE_PIN T5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 10.000 -name sys_clk [get_ports clk]
create_generated_clock -name cpu_clk -source [get_ports clk] -divide_by 2 \
    [get_pins u_clk/clk_out_reg/Q]

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property PACKAGE_PIN P15 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN N5 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]
set_property PACKAGE_PIN T4 [get_ports uart_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]
set_property PACKAGE_PIN R17 [get_ports key_next]
set_property IOSTANDARD LVCMOS33 [get_ports key_next]
set_property PACKAGE_PIN G6 [get_ports {anode[7]}]
set_property PACKAGE_PIN E1 [get_ports {anode[6]}]
set_property PACKAGE_PIN F1 [get_ports {anode[5]}]
set_property PACKAGE_PIN G1 [get_ports {anode[4]}]
set_property PACKAGE_PIN H1 [get_ports {anode[3]}]
set_property PACKAGE_PIN C1 [get_ports {anode[2]}]
set_property PACKAGE_PIN C2 [get_ports {anode[1]}]
set_property PACKAGE_PIN G2 [get_ports {anode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[*]}]
set_property PACKAGE_PIN D5 [get_ports {segment[7]}]
set_property PACKAGE_PIN B2 [get_ports {segment[6]}]
set_property PACKAGE_PIN B3 [get_ports {segment[5]}]
set_property PACKAGE_PIN A1 [get_ports {segment[4]}]
set_property PACKAGE_PIN B1 [get_ports {segment[3]}]
set_property PACKAGE_PIN A3 [get_ports {segment[2]}]
set_property PACKAGE_PIN A4 [get_ports {segment[1]}]
set_property PACKAGE_PIN B4 [get_ports {segment[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segment[*]}]

# Reset, keys and UART are asynchronous board interfaces. The RTL contains
# synchronizers for key_next and uart_rxd; display/UART outputs have no
# synchronous external receiver timing requirement.
set_false_path -from [get_ports {rst_n key_next uart_rxd}]
set_false_path -to [get_ports {uart_txd anode[*] segment[*]}]
