"""Remove only known generated work directories; preserve source and signoff evidence."""
from pathlib import Path
import shutil
ROOT=Path(__file__).resolve().parents[1]
def cleanup():
    removed=[]
    # These are generated by our Vivado/test entry points. Never infer disposability from references.
    names=["build/_sim","build/.Xil","ip/packager_work","ip/smoke/work",
           "vivado/asm_uart_2019_2.cache","vivado/asm_uart_2019_2.sim",
           "vivado/asm_uart_2019_2.hw","vivado/asm_uart_2019_2.runs",
           "vivado/asm_uart_2019_2.ip_user_files","tools/__pycache__"]
    for name in names:
        target=ROOT/name
        if not target.exists(): continue
        if target.is_symlink() or not target.resolve().is_relative_to(ROOT.resolve()):
            raise RuntimeError("Refusing path outside project: "+str(target))
        shutil.rmtree(target)
        removed.append(name)
    patterns=["*_stage.tcl","*_stage.log","*_stage_console.log","*.backup.log","*.backup.jou","*.jou","*.console.log"]
    for pattern in patterns:
        for target in (ROOT/"build").glob(pattern):
            if target.is_file() and target.resolve().is_relative_to(ROOT.resolve()):
                target.unlink();removed.append(target.relative_to(ROOT).as_posix())
    print("GENERATED_CLEANUP",len(removed),"items")
    return removed
if __name__=="__main__":cleanup()
